[server]
host_name = "localhost"
video_save_dir = "saves"
webserver_port = 8080
websocket_port = 9999

[camera]
url = "http://192.168.1.1/video.mjpeg"

[processing]
avg_weighting = 0.5
dilation_iterations = 0
fixed_lvl_threshold = 5
fps = 2
gauss_ksize = 7
pixel_threshold_hi = 9000
pixel_threshold_lo = 15

[alerting]
alarm_hysteresis_s = 60
alert_time_s = 180
end_time = "18:30"
initial_alarm_duration_m = 30
min_movement_s = 10
start_time = "19:22"

[alerters.siren]
[alerters.siren]
enabled = true
ssh_host = "192.168.1.1"
ssh_key_path = "app/alert_plugins/keys/id-rsa"
ssh_user = "user"
test_grp = true

[alerters.telegram]
api_key = "9999999999:XXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXX"
chat_ids = [
  "1111111111",
]
enabled = true
test_grp = true
